{% set name = "hecss" %}
{% set version = "0.3.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b99edb8a73187a9531af455a94fd624c6518f6752b96ce2b71132f0af721a77d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - hecss_sampler = hecss.cli:_hecss_sampler

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - tqdm
    - click
    - ase

test:
  imports:
    - hecss
    - hecss.core
  requires:
    - pip
  commands:
    - pip check
    - hecss_sampler --help

about:
  home: https://jochym.gitlab.io/hecss
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: High Efficiency Configuration Space Sampler
  description: |
    HECSS is a Markow chain Monte-Carlo, configuration space sampler using 
    Metropolis-Hastings algorithm for probablity distribution sampling. 
    It provides an alternative way to create representations of systems 
    at thermal equilibrium without running a very expensive molecular 
    dynamics simulation. The theoretical foundation of the code are presented 
    in the section [Background](https://jochym.gitlab.io/hecss/Background) 
    in the [Documentation](https://jochym.gitlab.io/hecss/). 
    More detailed examples are included in the 
    [LAMMPS](https://jochym.gitlab.io/hecss/LAMMPS_Tutorial) 
    and [VASP](https://jochym.gitlab.io/hecss/VASP_Tutorial) tutorials.
  doc_url: https://jochym.gitlab.io/hecss
  dev_url: https://gitlab.com/jochym/hecss

extra:
  recipe-maintainers:
    - jochym
